ALTER TABLE space ADD COLUMN access_mode VARCHAR(32) NOT NULL DEFAULT 'INVITE_ONLY';
ALTER TABLE space ADD CONSTRAINT chk_space_access_mode
  CHECK (access_mode IN ('INVITE_ONLY', 'AUTHENTICATED', 'PUBLIC'));
ALTER TABLE space ADD COLUMN sync_to_main_feed BOOLEAN NOT NULL DEFAULT TRUE;
