// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/ai_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/ai_service.proto.
 */
export const file_api_v1_ai_service: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvdjEvYWlfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIm4KE0dlbmVyYXRlVGV4dFJlcXVlc3QSGAoLcHJvdmlkZXJfaWQYASABKAlCA+BBAhISCgVtb2RlbBgCIAEoCUID4EEBEhMKBnByb21wdBgDIAEoCUID4EECEhQKB2NvbnRleHQYBCABKAlCA+BBASIkChRHZW5lcmF0ZVRleHRSZXNwb25zZRIMCgR0ZXh0GAEgASgJIkkKEVRyYW5zY3JpYmVSZXF1ZXN0EjQKBWF1ZGlvGAEgASgLMiAubWVtb3MuYXBpLnYxLlRyYW5zY3JpcHRpb25BdWRpb0ID4EECIncKElRyYW5zY3JpcHRpb25BdWRpbxIWCgdjb250ZW50GAEgASgMQgPgQQRIABINCgN1cmkYAiABKAlIABIVCghmaWxlbmFtZRgDIAEoCUID4EEBEhkKDGNvbnRlbnRfdHlwZRgEIAEoCUID4EEBQggKBnNvdXJjZSIiChJUcmFuc2NyaWJlUmVzcG9uc2USDAoEdGV4dBgBIAEoCTKXAgoJQUlTZXJ2aWNlEnkKClRyYW5zY3JpYmUSHy5tZW1vcy5hcGkudjEuVHJhbnNjcmliZVJlcXVlc3QaIC5tZW1vcy5hcGkudjEuVHJhbnNjcmliZVJlc3BvbnNlIijaQQVhdWRpb4LT5JMCGjoBKiIVL2FwaS92MS9haTp0cmFuc2NyaWJlEo4BCgxHZW5lcmF0ZVRleHQSIS5tZW1vcy5hcGkudjEuR2VuZXJhdGVUZXh0UmVxdWVzdBoiLm1lbW9zLmFwaS52MS5HZW5lcmF0ZVRleHRSZXNwb25zZSI32kEScHJvdmlkZXJfaWQscHJvbXB0gtPkkwIcOgEqIhcvYXBpL3YxL2FpOmdlbmVyYXRlVGV4dEKmAQoQY29tLm1lbW9zLmFwaS52MUIOQWlTZXJ2aWNlUHJvdG9QAVowZ2l0aHViLmNvbS91c2VtZW1vcy9tZW1vcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.GenerateTextRequest
 */
export type GenerateTextRequest = Message<"memos.api.v1.GenerateTextRequest"> & {
  /**
   * Required. Configured provider identifier.
   *
   * @generated from field: string provider_id = 1;
   */
  providerId: string;

  /**
   * Optional. Provider model identifier; uses a provider default when empty.
   *
   * @generated from field: string model = 2;
   */
  model: string;

  /**
   * Required. Instruction for the model.
   *
   * @generated from field: string prompt = 3;
   */
  prompt: string;

  /**
   * Optional. Current memo text supplied as editing context.
   *
   * @generated from field: string context = 4;
   */
  context: string;
};

/**
 * Describes the message memos.api.v1.GenerateTextRequest.
 * Use `create(GenerateTextRequestSchema)` to create a new message.
 */
export const GenerateTextRequestSchema: GenMessage<GenerateTextRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 0);

/**
 * @generated from message memos.api.v1.GenerateTextResponse
 */
export type GenerateTextResponse = Message<"memos.api.v1.GenerateTextResponse"> & {
  /**
   * Generated Markdown-compatible text.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.GenerateTextResponse.
 * Use `create(GenerateTextResponseSchema)` to create a new message.
 */
export const GenerateTextResponseSchema: GenMessage<GenerateTextResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 1);

/**
 * @generated from message memos.api.v1.TranscribeRequest
 */
export type TranscribeRequest = Message<"memos.api.v1.TranscribeRequest"> & {
  /**
   * Required. Audio input.
   *
   * @generated from field: memos.api.v1.TranscriptionAudio audio = 1;
   */
  audio?: TranscriptionAudio | undefined;
};

/**
 * Describes the message memos.api.v1.TranscribeRequest.
 * Use `create(TranscribeRequestSchema)` to create a new message.
 */
export const TranscribeRequestSchema: GenMessage<TranscribeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 2);

/**
 * @generated from message memos.api.v1.TranscriptionAudio
 */
export type TranscriptionAudio = Message<"memos.api.v1.TranscriptionAudio"> & {
  /**
   * @generated from oneof memos.api.v1.TranscriptionAudio.source
   */
  source: {
    /**
     * Inline audio bytes.
     *
     * @generated from field: bytes content = 1;
     */
    value: Uint8Array;
    case: "content";
  } | {
    /**
     * URI for audio content. Reserved for future use.
     *
     * @generated from field: string uri = 2;
     */
    value: string;
    case: "uri";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. The uploaded filename.
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * Optional. The MIME type of the input audio.
   *
   * @generated from field: string content_type = 4;
   */
  contentType: string;
};

/**
 * Describes the message memos.api.v1.TranscriptionAudio.
 * Use `create(TranscriptionAudioSchema)` to create a new message.
 */
export const TranscriptionAudioSchema: GenMessage<TranscriptionAudio> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 3);

/**
 * @generated from message memos.api.v1.TranscribeResponse
 */
export type TranscribeResponse = Message<"memos.api.v1.TranscribeResponse"> & {
  /**
   * The transcribed text.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.TranscribeResponse.
 * Use `create(TranscribeResponseSchema)` to create a new message.
 */
export const TranscribeResponseSchema: GenMessage<TranscribeResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 4);

/**
 * @generated from service memos.api.v1.AIService
 */
export const AIService: GenService<{
  /**
   * Transcribe transcribes an audio file using an instance AI provider.
   *
   * @generated from rpc memos.api.v1.AIService.Transcribe
   */
  transcribe: {
    methodKind: "unary";
    input: typeof TranscribeRequestSchema;
    output: typeof TranscribeResponseSchema;
  },
  /**
   * GenerateText generates memo-ready text using an instance AI provider.
   *
   * @generated from rpc memos.api.v1.AIService.GenerateText
   */
  generateText: {
    methodKind: "unary";
    input: typeof GenerateTextRequestSchema;
    output: typeof GenerateTextResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_ai_service, 0);

