// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/poll_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { PollSchema } from "./memo_service_pb";
import { file_api_v1_memo_service } from "./memo_service_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import { file_google_api_resource } from "../../google/api/resource_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/poll_service.proto.
 */
export const file_api_v1_poll_service: GenFile = /*@__PURE__*/
  fileDesc("ChlhcGkvdjEvcG9sbF9zZXJ2aWNlLnByb3RvEgxtZW1vcy5hcGkudjEiVQoSR2V0TWVtb1BvbGxSZXF1ZXN0EicKBG5hbWUYASABKAlCGeBBAvpBEwoRbWVtb3MuYXBpLnYxL01lbW8SFgoJZGV2aWNlX2lkGAIgASgJQgPgQQEiawoPVm90ZU1lbW9SZXF1ZXN0EicKBG5hbWUYASABKAlCGeBBAvpBEwoRbWVtb3MuYXBpLnYxL01lbW8SFwoKb3B0aW9uX2lkcxgCIAMoCUID4EECEhYKCWRldmljZV9pZBgDIAEoCUID4EEBMvwBCgtQb2xsU2VydmljZRJvCgtHZXRNZW1vUG9sbBIgLm1lbW9zLmFwaS52MS5HZXRNZW1vUG9sbFJlcXVlc3QaEi5tZW1vcy5hcGkudjEuUG9sbCIq2kEEbmFtZYLT5JMCHRIbL2FwaS92MS97bmFtZT1tZW1vcy8qfS9wb2xsEnwKCFZvdGVNZW1vEh0ubWVtb3MuYXBpLnYxLlZvdGVNZW1vUmVxdWVzdBoSLm1lbW9zLmFwaS52MS5Qb2xsIj3aQQ9uYW1lLG9wdGlvbl9pZHOC0+STAiU6ASoiIC9hcGkvdjEve25hbWU9bWVtb3MvKn0vcG9sbDp2b3RlQqgBChBjb20ubWVtb3MuYXBpLnYxQhBQb2xsU2VydmljZVByb3RvUAFaMGdpdGh1Yi5jb20vdXNlbWVtb3MvbWVtb3MvcHJvdG8vZ2VuL2FwaS92MTthcGl2MaICA01BWKoCDE1lbW9zLkFwaS5WMcoCDE1lbW9zXEFwaVxWMeICGE1lbW9zXEFwaVxWMVxHUEJNZXRhZGF0YeoCDk1lbW9zOjpBcGk6OlYxYgZwcm90bzM", [file_api_v1_memo_service, file_google_api_annotations, file_google_api_client, file_google_api_field_behavior, file_google_api_resource]);

/**
 * @generated from message memos.api.v1.GetMemoPollRequest
 */
export type GetMemoPollRequest = Message<"memos.api.v1.GetMemoPollRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Existing browser identifier, used to recover a guest's voting state.
   *
   * @generated from field: string device_id = 2;
   */
  deviceId: string;
};

/**
 * Describes the message memos.api.v1.GetMemoPollRequest.
 * Use `create(GetMemoPollRequestSchema)` to create a new message.
 */
export const GetMemoPollRequestSchema: GenMessage<GetMemoPollRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_poll_service, 0);

/**
 * @generated from message memos.api.v1.VoteMemoRequest
 */
export type VoteMemoRequest = Message<"memos.api.v1.VoteMemoRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: repeated string option_ids = 2;
   */
  optionIds: string[];

  /**
   * Required for guest voting. The web client stores a random opaque value.
   *
   * @generated from field: string device_id = 3;
   */
  deviceId: string;
};

/**
 * Describes the message memos.api.v1.VoteMemoRequest.
 * Use `create(VoteMemoRequestSchema)` to create a new message.
 */
export const VoteMemoRequestSchema: GenMessage<VoteMemoRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_poll_service, 1);

/**
 * @generated from service memos.api.v1.PollService
 */
export const PollService: GenService<{
  /**
   * @generated from rpc memos.api.v1.PollService.GetMemoPoll
   */
  getMemoPoll: {
    methodKind: "unary";
    input: typeof GetMemoPollRequestSchema;
    output: typeof PollSchema;
  },
  /**
   * @generated from rpc memos.api.v1.PollService.VoteMemo
   */
  voteMemo: {
    methodKind: "unary";
    input: typeof VoteMemoRequestSchema;
    output: typeof PollSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_poll_service, 0);

